name=input("Enter your Name\n")
branch=input("Enter your branch\n")
age=int(input("Enter your age\n"))
gender=input("Enter your gender\n")
institute=input("Enter your collagename\n")
print("Name:-",name)
print("Branch:-",branch)
print("Age:-",age)
print("Gender:-",gender)
print("Institute:-",institute)
